# Lupi's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

wolf:
    enable: true # Allow wolves to spawn naturally.
    item: 352 # Item to select a tamed wolf.
    friendly: false # Make wild wolves friendly. Wolves can still attack player when they are tame.
    pvp: false # Set wolf to not attack players when pvp is off.
    limit: 0 # Enable limit? 0 for disable and higher to enable.
    keepchunksloaded: false # Keep chunks with tamed wolf's in loaded.

info:
    item: 340 # Item to show info about a tamed wolf.

inventory:
    enable: true # Use wolf inventory?
    item: 54 # Item for open/add wolf inventory.
    armor: true # Enable wolf armor.	