name: halvors
main: org.halvors.halvors.halvors
version: 0.0.1
description: 
author: halvors
website: halvors.org
database: true

commands:
    armor:
        aliases: [a]
        description:
        usage:

    ban:
        aliases:
        description:
        usage:

    bank:
        aliases:
        description:
        usage:

    ci:
        aliases:
        description:
        usage:

    help:
        aliases: [hjelp]
        description:
        usage: 

    kick:
        aliases:
        description:
        usage:

    maintenance:
        aliases:
        description:
        usage:

    setspawn:
        aliases:
        description:
        usage:

    spawn:
        aliases:
        description:
        usage:

    stuck:
        aliases: [s]
        description:
        usage:

    time:
        aliases: [tid]
        description:
        usage:
    
    tp:
        aliases:
        description:
        usage:
    
    tphere: [tph]
        aliases:
        description:
        usage:

permissions:
    halvors.*:
        default: op
        description:
        children:
            halvors.*: true
            halvors.armor: true
            halvors.ban: true
            halvors.bank: true
            halvors.ci: true
            halvors.help: true
            halvors.kick: true
            halvors.maintenance: true
            halvors.setspawn: true
            halvors.spawn: true
            halvors.stuck: true
            halvors.time: true
            halvors.tp: true
            halvors.tphere: true 
    
    halvors.armor:
        description:

    halvors.ban:
        description:

    halvors.bank:
        description:

    halvors.ci:
        description:

    halvors.help:
        description:

    halvors.kick:
        description:

    halvors.maintenance:
        description:

    halvors.setspawn:
        description:

    halvors.spawn:
        description:

    halvors.stuck:
        description:

    halvors.time:
        description:

    halvors.tp:
        description:

    halvors.tphere: 
        description:
