name: halvors
main: org.halvors.halvors.halvors
version: 0.1
description: 
author: halvors
website: halvors.org

commands:
    armor:
        aliases:
        description:
        usage:

    bank:
        aliases:
        description:
        usage:

    ci:
        aliases:
        description:
        usage:

    help:
        aliases: [hjelp]
        description:
        usage:

    loc:
        aliases: [loc]
        description:
        usage:

    maintenance:
        aliases:
        description:
        usage:

    setspawn:
        aliases:
        description:
        usage:

    spawn:
        aliases:
        description:
        usage:

    stuck:
        aliases: [s]
        description:
        usage:

    time:
        aliases: [tid]
        description:
        usage:

permissions:
    halvors.*:
        default: op
        description:
        children:
            halvors.group.*: true            

            halvors.armor: true
            halvors.ban: true
            halvors.bank: true
            halvors.ci: true
            halvors.help: true
            halvors.kick: true
            halvors.maintenance: true
            halvors.setspawn: true
            halvors.spawn: true
            halvors.stuck: true
            halvors.time: true
            halvors.tp: true
            halvors.tphere: true 
    
    halvors.armor:
        description:    

    halvors.ban:
        description:

    halvors.bank:
        description:

    halvors.ci:
        description:

    halvors.help:
        description:

    halvors.kick:
        description:

    halvors.maintenance:
        description:

    halvors.setspawn:
        description:

    halvors.spawn:
        description:

    halvors.stuck:
        description:

    halvors.time:
        description:

    halvors.tp:
        description:

    halvors.tphere: 
        description:

    halvors.group.*:
        description:
        children:
            halvors.group.admin: true
            halvors.group.mod: true

    halvors.group.admin:
        description:

    halvors.group.mod:
        description: