name: IndustrialNorge
main: no.industrialnorge.industrialnorge.IndustrialNorge
version: 0.0.1
description: Bukkit plugin for IndustrialNorge serveren.
author: halvors
website: http://halvors.org/servere/minecraft/industialnorge

commands:
    armor:
        aliases:
        description: Lar deg sette blokker og items på hodet.
        usage: /<command>

    ci:
        aliases:
        description: Fjerner alt i ditt inventory.
        usage: /<command>

    list:
        aliases: [who]
        description: Viser en liste med påloggede spillere.
        usage: /<command>

    loc:
        aliases: [lok]
        description: Viser din nåværende posisjon.
        usage: /<command>

    mods:
        aliases:
        description: Viser en lite over moddene serveren kjører.
        usage: /<command>

    setspawn:
        aliases:
        description: Setter spawn for din nåværende verden.
        usage: /<command>

    spawn:
        aliases:
        description: Teleporterer deg til din verdens spawn.
        usage: /<command>

    stuck:
        aliases: [s]
        description: Flytter deg til høyeste blokk i verden, nyttig om du er stuck inni en blokk.
        usage: /<command>

permissions:
    industrialnorge.*:
        default: op
        description: 
        children:
            industrialnorge.group.*: true            

            industrialnorge.armor: true
            industrialnorge.ci: true
            industrialnorge.ci.others: true
            industrialnorge.list: true
            industrialnorge.loc: true
            industrialnorge.mods: true
            industrialnorge.setspawn: true
            industrialnorge.spawn: true
            industrialnorge.stuck: true

    industrialnorge.armor:
        description:
    
    industrialnorge.ci:
        description:
        
    industrialnorge.ci.others:
        description:
    
    industrialnorge.list:
        description:
        
    industrialnorge.loc:
        description:
        
    industrialnorge.mods:
        description:

    industrialnorge.setspawn:
        description: 
        
    industrialnorge.spawn:
        description: 

    industrialnorge.stuck:
        description:

    industrialnorge.group.*:
        description:
        children:
            industrialnorge.group.admin: true
            industrialnorge.group.mod: true

    industrialnorge.group.admin:
        description:

    industrialnorge.group.mod:
        description: