name: IndustrialNorge
main: no.industrialnorge.industrialnorge.IndustrialNorge
version: 0.1
description: 
author: halvors
website: halvors.org

commands:
    armor:
        aliases:
        description: Lar deg sette blokker og items på hodet.
        usage: /<command>

    list:
        aliases: [who]
        description: Viser alle spillere på serveren.
        usage: /<command>

    loc:
        aliases: [lok]
        description: Viser din nåværende posisjon.
        usage: /<command>

    stuck:
        aliases: [s]
        description: Flytter deg til høyeste blokk i verden, nyttig om du er stuck inni en blokk.
        usage: /<command>

permissions:
    industrialnorge.*:
        default: op
        description:
        children:
            industrialnorge.group.*: true            

            industrialnorge.armor: true
            industrialnorge.list: true
            industrialnorge.loc: true
            industrialnorge.stuck: true
    
    industrialnorge.armor:
        description:

    industrialnorge.list:
        description: 
        
    industrialnorge.loc:
        description:

    industrialnorge.stuck:
        description:

    industrialnorge.group.*:
        description:
        children:
            industrialnorge.group.admin: true
            industrialnorge.group.mod: true

    industrialnorge.group.admin:
        description:

    industrialnorge.group.mod:
        description: