name: halvors
main: org.halvors.halvors.halvors
version: 0.0.1
description: 
author: halvors
website: halvors.org

commands:
    help:
        aliases: [hjelp]
        description:
        usage: 

    stuck:
        aliases: [s]
        description:
        usage:

    time:
        aliases: [tid]
        description:
        usage:
        
    armor:
        aliases: [a]
        description:
        usage:

    hkick:
        aliases:
        description:
        usage:

    hban:
        aliases:
        description:
        usage:
        
permissions:
    halvors.*:
        default: op
        description: 
        children: 
            halvors.users.*: true
            halvors.admin.*: true
        
    halvors.users.*:
        description:
        children:
            halvors.users.help: true
            halvors.users.stuck: true
            halvors.users.tid: true
    
    halvors.users.help:
        description:
    halvors.users.stuck:
        description:
    halvors.users.time:
        description:
        
    halvors.admin.*:
        description:
        children:
            halvors.admin.armor: true
            halvors.admin.kick: true
            halvors.admin.ban: true
    
    halvors.admin.armor:
        description:
            
    halvors.admin.kick:
        description:
        
    halvors.admin.ban:
        description: