name: IndustrialNorge
main: no.industrialnorge.industrialnorge.IndustrialNorge
version: 0.1
description: 
author: halvors
website: halvors.org

commands:
    armor:
        aliases:
        description: Lar deg sette blokker og items på hodet.
        usage: /<command>

    loc:
        aliases: [lok]
        description: Viser din nåværende posisjon.
        usage: /<command>

    setspawn:
        aliases:
        description: Setter spawn i din nåværende verden.
        usage: /<command>
        
    spawn:
        aliases:
        description: Teleporterer deg til din verdens spawn.
        usage: /<command>

    stuck:
        aliases: [s]
        description: Flytter deg til høyeste blokk i verden, nyttig om du er stuck inni en blokk.
        usage: /<command>

permissions:
    industrialnorge.*:
        default: op
        description:
        children:
            industrialnorge.group.*: true            

            industrialnorge.armor: true
            industrialnorge.loc: true
            industrialnorge.setspawn: true
            industrialnorge.spawn: true
            industrialnorge.stuck: true
    
    industrialnorge.armor:
        description:
        
    industrialnorge.loc:
        description:

    industrialnorge.setspawn:
        description: 
        
    industrialnorge.spawn:
        description: 

    industrialnorge.stuck:
        description:

    industrialnorge.group.*:
        description:
        children:
            industrialnorge.group.admin: true
            industrialnorge.group.mod: true

    industrialnorge.group.admin:
        description:

    industrialnorge.group.mod:
        description: