package no.industrialnorge.industrialnorge.util;

import org.bukkit.Material;

public class ArmorUtils {
	public static boolean isAllowed(Material type) {
		return type.equals(Material.BOOKSHELF)
		    || type.equals(Material.BRICK)
			|| type.equals(Material.CACTUS)
			|| type.equals(Material.CHEST)
			|| type.equals(Material.CLAY)
			|| type.equals(Material.COAL_ORE)
			|| type.equals(Material.COBBLESTONE)
			|| type.equals(Material.COBBLESTONE_STAIRS)
			|| type.equals(Material.DETECTOR_RAIL)
			|| type.equals(Material.DIAMOND_BLOCK)
			|| type.equals(Material.DIAMOND_ORE)
			|| type.equals(Material.DIRT)
			|| type.equals(Material.DISPENSER)
			|| type.equals(Material.DOUBLE_STEP)
			|| type.equals(Material.FENCE)
			|| type.equals(Material.FIRE)
			|| type.equals(Material.FURNACE)
			|| type.equals(Material.GLASS)
			|| type.equals(Material.GLOWSTONE)
			|| type.equals(Material.GOLD_BLOCK)
			|| type.equals(Material.GOLD_ORE)
			|| type.equals(Material.GRASS)
			|| type.equals(Material.GRAVEL)
			|| type.equals(Material.ICE)
			|| type.equals(Material.IRON_BLOCK)
			|| type.equals(Material.IRON_ORE)
			|| type.equals(Material.JACK_O_LANTERN)
			|| type.equals(Material.JUKEBOX)
			|| type.equals(Material.LADDER)
			|| type.equals(Material.LAPIS_BLOCK)														
			|| type.equals(Material.LEAVES)
			|| type.equals(Material.LOCKED_CHEST)
			|| type.equals(Material.LOG)
			|| type.equals(Material.MOB_SPAWNER)
			|| type.equals(Material.MOSSY_COBBLESTONE)
			|| type.equals(Material.NETHERRACK)
			|| type.equals(Material.NOTE_BLOCK)
			|| type.equals(Material.OBSIDIAN)
			|| type.equals(Material.PISTON_BASE)
			|| type.equals(Material.PISTON_STICKY_BASE)
			|| type.equals(Material.POWERED_RAIL)
			|| type.equals(Material.RAILS)
			|| type.equals(Material.SAND)
			|| type.equals(Material.SANDSTONE)
			|| type.equals(Material.SIGN)
			|| type.equals(Material.SIGN_POST)
			|| type.equals(Material.SNOW_BLOCK)
			|| type.equals(Material.SOIL)
			|| type.equals(Material.SOUL_SAND)
			|| type.equals(Material.STEP)
			|| type.equals(Material.STONE)
			|| type.equals(Material.TNT)
			|| type.equals(Material.WALL_SIGN)
			|| type.equals(Material.WEB) 
			|| type.equals(Material.WOOD)
			|| type.equals(Material.WOOD_STAIRS)
			|| type.equals(Material.WOOL)
			|| type.equals(Material.WORKBENCH);
	}
}